name: dotnet

on:
  push:
    branches:
      - '**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

    branches:
      - main

  release:
    types:
      - published

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request'

    strategy:
      matrix:
        dotnet: [ '6.0.x' ]

    outputs:
      version: "${{ steps.version.outputs.majorMinorPatch }}"
      commitsSinceVersion: "${{ steps.version.outputs.commitsSinceVersionSourcePadded }}"
      sha: "sha.${{ steps.version.outputs.sha }}"

    name: Test dotnet ${{ matrix.dotnet }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Get Version
        id: version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - run: dotnet restore

      - run: dotnet build --no-restore --configuration Release

      - run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Upload Coverage to Codecov;
        uses: codecov/codecov-action@v2

  release:
    runs-on: ubuntu-latest
    if: |
      !github.event.release.prerelease

    needs:
      - test

    strategy:
      matrix:
        dotnet: [ '6.0.x' ]

    name: Release
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }} # SDK Version to use.
          source-url: https://nuget.pkg.github.com/idarboss/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - run: dotnet build --configuration Release /p:VersionPrefix=${{ needs.test.outputs.version }} /p:InformationalVersion=${{ needs.test.outputs.version }}-${{ needs.test.outputs.sha }}

      - name: Create the package
        run: dotnet pack --configuration Release -o dist /p:PackageVersion=${{ needs.test.outputs.version }}

      - name: Publish the package to GPR
        run: dotnet nuget push dist/*.nupkg

  pre-release:
    runs-on: ubuntu-latest
    if: |
      github.event.release.prerelease

    needs:
      - test

    strategy:
      matrix:
        dotnet: [ '6.0.x' ]

    name: Pre-Release
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }} # SDK Version to use.
          source-url: https://nuget.pkg.github.com/idarboss/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - run: dotnet build --configuration Release /p:VersionPrefix=${{ needs.test.outputs.version }} /p:VersionSuffix="preview" /p:InformationalVersion=${{ needs.test.outputs.version }}-preview.${{ needs.test.outputs.sha }}

      - name: Create the package
        run: dotnet pack --configuration Release -o dist /p:PackageVersion=${{ needs.test.outputs.version }}-preview${{ needs.test.outputs.CommitsSinceVersionSourcePadded }}

      - name: Publish the package to GPR
        run: dotnet nuget push dist/*.nupkg
